# .circleci/config.yml
version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3
    parallelism: 2
    steps:
      - checkout
      - run: pip install -e ".[dev]"
      - run: pip install -r requirements/tests.txt
      - run:
          command: |
            pytest --cov-config=setup.cfg --cov=src --cov-report=html --junit-xml=test-results/test-results.xml --circleci-parallelize
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: htmlcov
          destination: flask-coverage

workflows:
  version: 2
  test:
    jobs:
      - test