# .circleci/config.yml
version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3
    parallelism: 2
    steps:
      - checkout
      - run: pip install -e ".[dev]"
      - run: pip install -r requirements/tests.txt
      - run: pytest
workflows:
  version: 2
  test:
    jobs:
      - test